/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Modelo.Clientes;
import Modelo.PegarTudo;

/**
 *
 * @author Castelhano
 */
public class TelaVer extends javax.swing.JFrame {
    
    private Clientes paciente;
    
     public Clientes getPaciente() {
        return paciente;
    }

    public void setPaciente(Clientes paciente) {
        this.paciente = paciente;
    }
    public void mostrar(){
       TXTNOME.setText(paciente.getNome());
       TXTIDADE.setText(String.valueOf(paciente.getEndereco()));
       TXTCPF.setText(paciente.getEmail());
       jLstatus.setText(paciente.getCidade());
       jLsexo.setText(paciente.getBairro());
   }
    
    

    /**
     * Creates new form TelaVer
     */
    public TelaVer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TXTCPF = new javax.swing.JLabel();
        TXTNOME = new javax.swing.JLabel();
        TXTIDADE = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLstatus = new javax.swing.JLabel();
        jLsexo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Email :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 230, 44, 18);

        TXTCPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TXTCPF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(TXTCPF);
        TXTCPF.setBounds(100, 220, 227, 25);

        TXTNOME.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TXTNOME.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(TXTNOME);
        TXTNOME.setBounds(100, 110, 227, 29);

        TXTIDADE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TXTIDADE.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(TXTIDADE);
        TXTIDADE.setBounds(100, 160, 227, 27);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Cidade :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 280, 60, 18);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Bairro :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 340, 60, 18);

        jLstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLstatus.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLstatus);
        jLstatus.setBounds(100, 270, 158, 26);

        jLsexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLsexo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLsexo);
        jLsexo.setBounds(100, 330, 160, 27);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Endereço :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 170, 70, 18);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Nome :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 120, 50, 18);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/doctor1.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 0, 390, 490);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("Rede canal");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 10, 140, 29);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 50, 340, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TXTCPF;
    private javax.swing.JLabel TXTIDADE;
    private javax.swing.JLabel TXTNOME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLsexo;
    private javax.swing.JLabel jLstatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

   

   
}
