package Apresentacao;

import Apresentacao.TelaPrincipal.Hora;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Castelhano
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    public boolean estaFechado(Object obj){
        JInternalFrame[] ativo = jDesktop.getAllFrames();
        boolean fechado = true;
        int i = 0;
        
        while(i < ativo.length && fechado){
            if(ativo[i] == obj){
                fechado = false;
            }
            i++;
        }
        return fechado;
    }
    
    int id_tabela;// Tela Tabela
    int id_cuidador;

    
    /**
     * Creates new form .TelaPrincipal
     */
    public TelaPrincipal(String user, int id, String permissao, int idTabela, int idCuidador) {
        initComponents();
        jLid.setText(String.valueOf(id));
        jLusuario.setText(user);
        jLpermissao.setText(permissao);
        
        if(jLpermissao.getText().equals("Administrador")){
            jMenuUsuario.setEnabled(true);
        }else{
            jMenuUsuario.setEnabled(false);
            jMeRegistro.setEnabled(false);
        }
         this.id_tabela=idTabela;
         this.id_cuidador=idCuidador;
    }
    

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLusuario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jDesktop = new javax.swing.JDesktopPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLpermissao = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLdata = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLhora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMtabela = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMCadastro = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenSobre = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenu();
        jMusuario = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMlogar = new javax.swing.JMenuItem();
        jMeRegistro = new javax.swing.JMenu();
        jMenuIRegistro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID :");

        jLid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLid.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nome :");

        jLusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLusuario.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLid)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLid)
                    .addComponent(jLabel3)
                    .addComponent(jLusuario))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 660, 1390, 90);

        jDesktop.setBackground(new java.awt.Color(102, 153, 255));
        jDesktop.setForeground(new java.awt.Color(102, 153, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dados Pessoais");

        jLpermissao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLpermissao.setForeground(new java.awt.Color(255, 255, 255));
        jLpermissao.setText("jLabel9");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data :");

        jLdata.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLdata.setForeground(new java.awt.Color(255, 255, 255));
        jLdata.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hora:");

        jLhora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLhora.setForeground(new java.awt.Color(255, 255, 255));
        jLhora.setText("jLabel8");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLpermissao, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLdata, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jLhora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLpermissao)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLdata))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLhora))
                .addContainerGap())
        );

        jDesktop.add(jPanel5);
        jPanel5.setBounds(10, 20, 190, 150);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/homeca.jpg"))); // NOI18N
        jDesktop.add(jLabel2);
        jLabel2.setBounds(0, 0, 1390, 659);

        getContentPane().add(jDesktop);
        jDesktop.setBounds(0, 0, 1390, 660);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenu/archive (1).png"))); // NOI18N
        jMenu1.setText("Arquivo");

        jMtabela.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMtabela.setText("Tabela");
        jMtabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMtabelaActionPerformed(evt);
            }
        });
        jMenu1.add(jMtabela);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenu/paciente.png"))); // NOI18N
        jMenu2.setText("Cliente");

        jMCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMCadastro.setText("Cadastro");
        jMCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastroActionPerformed(evt);
            }
        });
        jMenu2.add(jMCadastro);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenu/sobre.png"))); // NOI18N
        jMenu3.setText("Sobre");

        jMenSobre.setText("Sobre");
        jMenSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenSobreActionPerformed(evt);
            }
        });
        jMenu3.add(jMenSobre);

        jMenuBar1.add(jMenu3);

        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenu/cuidador.png"))); // NOI18N
        jMenuUsuario.setText("Usuario");

        jMusuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMusuario.setText("Usuario");
        jMusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMusuarioActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMusuario);

        jMenuBar1.add(jMenuUsuario);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenu/permissao.png"))); // NOI18N
        jMenu5.setText("Desconectar");

        jMlogar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMlogar.setText("Logar com outro usuario");
        jMlogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMlogarActionPerformed(evt);
            }
        });
        jMenu5.add(jMlogar);

        jMenuBar1.add(jMenu5);

        jMeRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensMenu/register.png"))); // NOI18N
        jMeRegistro.setText("Registro");

        jMenuIRegistro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuIRegistro.setText("Registro");
        jMenuIRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIRegistroActionPerformed(evt);
            }
        });
        jMeRegistro.add(jMenuIRegistro);

        jMenuBar1.add(jMeRegistro);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 1407, 805);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Date datasistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jLdata.setText(formato.format(datasistema));
        
        Timer timer = new Timer(1000, new Hora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void jMlogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMlogarActionPerformed
        int opcao;
        opcao = JOptionPane.showConfirmDialog(null,"Deseja entrar com outro usuario",
                "Fechar",JOptionPane.YES_NO_OPTION);
        if(opcao == JOptionPane.YES_NO_OPTION){
            TelaLogin login = new TelaLogin();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMlogarActionPerformed

    Apresentacao.TelaClientes clientes;
    private void jMCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastroActionPerformed
        if(estaFechado(clientes)){
            clientes = new TelaClientes(jLusuario.getText());
            jDesktop.add(clientes).setLocation(150, 30);
            clientes.show();
            clientes.toFront();
        }else{
            clientes.show();
            clientes.toFront();
        }
    }//GEN-LAST:event_jMCadastroActionPerformed

    Apresentacao.TelaTabela tabela;
    private void jMtabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMtabelaActionPerformed
        if(estaFechado(tabela)){
            tabela = new TelaTabela(jLusuario.getText());
            tabela = new TelaTabela(jLusuario.getText());
            tabela.enviar(id_tabela);
            jDesktop.add(tabela).setLocation(150, 30);
            tabela.show();
        }else{
            tabela.show();
            tabela.toFront();
        }
    }//GEN-LAST:event_jMtabelaActionPerformed

    Apresentacao.TelaRegistro registro;
    private void jMenuIRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIRegistroActionPerformed
        if(estaFechado(registro)){
            registro = new TelaRegistro();
            jDesktop.add(registro).setLocation(150, 30);
            registro.show();
        }else{
            registro.show();
            registro.toFront();
        }
    }//GEN-LAST:event_jMenuIRegistroActionPerformed

    Apresentacao.TelaUsuario usuario;
    private void jMusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMusuarioActionPerformed
        if(estaFechado(usuario)){
            usuario = new TelaUsuario();
            jDesktop.add(usuario).setLocation(150, 30);
            usuario.show();
        }else{
            usuario.show();
            usuario.toFront();
        }
    }//GEN-LAST:event_jMusuarioActionPerformed
    
    Apresentacao.TelaSobre sobre;
    private void jMenSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenSobreActionPerformed
         if(estaFechado(sobre)){
            sobre = new TelaSobre();
            jDesktop.add(sobre).setLocation(150, 30);
            sobre.show();
        }else{
            sobre.show();
            sobre.toFront();
        }
    }//GEN-LAST:event_jMenSobreActionPerformed
        public class Hora implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            Calendar agora = Calendar.getInstance();
            jLhora.setText(String.format("%1$tH:%1$tM:%1$tS", agora));
        }
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLdata;
    private javax.swing.JLabel jLhora;
    private javax.swing.JLabel jLid;
    private javax.swing.JLabel jLpermissao;
    private javax.swing.JLabel jLusuario;
    private javax.swing.JMenuItem jMCadastro;
    private javax.swing.JMenu jMeRegistro;
    private javax.swing.JMenuItem jMenSobre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuIRegistro;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JMenuItem jMlogar;
    private javax.swing.JMenuItem jMtabela;
    private javax.swing.JMenuItem jMusuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
